services:
  hermes-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: hermes-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.hermes.gonalu.com/api
